# Generated by Django 3.2.9 on 2021-11-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='player_id',
            new_name='player',
        ),
    ]
