# Generated by Django 3.2.9 on 2021-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_auto_20211102_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='categories', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_url',
            field=models.ImageField(upload_to=None),
        ),
    ]
