# Generated by Django 3.2.9 on 2021-11-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0003_auto_20211105_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='entry',
            new_name='review',
        ),
    ]
