# Generated by Django 3.2.9 on 2021-11-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='picture',
            name='action_pic',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='gamerraterapi.game'),
        ),
    ]
